//tag::ref-doc[]
= Composed Task Runner

A task that executes a tasks in a directed graph as specified by a DSL that is
passed in via the `--graph` command line argument.

== Overview
The Composed Task Runner parses the graph DSL and for each node in the graph it
will execute a restful call against a specified http://docs.spring.io/spring-cloud-dataflow/docs/current/reference/htmlsingle/[Spring Cloud Data Flow]
instance to launch the associated task definition.  For each task definition that is executed the
Composed Task Runner will poll the database to verify that the task completed.
Once complete the Composed Task Runner will either continue to the next task in
the graph or fail based on how the DSL specified the sequence of tasks should
be executed.

== Graph DSL
<TBD>


== Traversing the graph
Composed Task Runner is built using
http://docs.spring.io/spring-batch/reference/html/[Spring Batch]
to execute the directed graph.   As such each node in the graph is a
http://docs.spring.io/spring-batch/reference/html/domain.html#domainStep[Step].
As discussed in the overview, each step in the graph will post a request to a
Spring Cloud Data Flow Server to execute a task definition.  Each Step has a
ComposedTaskStepExecutionListener associated with it, such that once the step
has been executed the
http://docs.spring.io/spring-batch/reference/htmlsingle/#stepExecutionListener[StepExecutionListener]
monitors the database awaiting the task to complete.  If the task launched by
the step fails to complete within the time specified by the `max-wait-time`
property, the
http://docs.spring.io/spring-batch/trunk/apidocs/org/springframework/batch/core/ExitStatus.html[ExitStatus]
of the Step will be set to UNKNOWN.  Once task launched by the step completes,
the StepExecutionListener will set the ExitStatus of that step based on the following rules:

* If the TaskExecution has an ExitMessage that will be used as the ExitStatus
* If no ExitMessage is present and the ExitCode is set to 0 then the ExitStatus
for the step will be COMPLETED.
* If no ExitMessage is present and the ExitCode is set to 1 then the ExitStatus
for the step will be FAILED.

If the state of any step in the graph is set to  FAILED and is not handled by
the DSL the Directed Graph execution will terminate.


== Usage
`java -jar composedtaskrunner-task-1.1.1.BUILD-SNAPSHOT.jar --graph=<your graph syntax>`

== Options

// see syntax (soon to be automatically generated) in spring-cloud-stream starters
The **$$ComposedTaskRunner$$** $$task$$ has the following options:

//tag::configuration-properties[]
$$composed-task-arguments$$:: $$The arguments to be used for each of the tasks.$$ *($$String$$, default: `$$<none>$$`)*
$$composed-task-properties$$:: $$The properties to be used for each of the tasks as well as their deployments.$$ *($$String$$, default: `$$<none>$$`)*
$$data-flow-uri$$:: $$The URI for the dataflow server that will receive task launch requests.$$ *($$URI$$, default: `$$<none>$$`)*
$$graph$$:: $$The DSL for the composed task directed graph.$$ *($$String$$, default: `$$<none>$$`)*
$$interval-time-between-checks$$:: $$The amount of time in millis that the ComposedTaskStepExecutionListener
 will wait between checks of the database to see if a task has completed.$$ *($$Integer$$, default: `$$500$$`)*
$$max-wait-time$$:: $$The maximum amount of time in millis that a individual step can run before
 the execution of the Composed task is failed.$$ *($$Integer$$, default: `$$30000$$`)*
//end::configuration-properties[]

//end::ref-doc[]
